name: Build and deploy Node.js app to Azure Web App - zenith-portal-web

on:
  push:
    branches:
      - Rel12.2
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Match your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build  
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A709E3260FAB4CA4BC4A3D203D455B1A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_323C249F64C140E4A9F379F578AA54F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1F5F9076F2AE4510A5F44323D52DF2DF }}

      - name: Zip files preserving symlinks
        run: |
         zip -r deploy.zip .next node_modules package.json public next.config.js
        
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app5'
          slot-name: 'Production'
          package: deploy.zip
